api/v1/polls/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import PollViewSet, PollSinglListCreate, QuestionSinglListCreate, PollSinglUpdateDestroyAPIView, \
    QuestionSinglUpdateDestroyAPIView, WriteUserChoiceIDSinglUpdateDestroyAPIView

#router = DefaultRouter()
#router.register(r'apipolls', PollViewSet, basename='apipolls')

urlpatterns = [
    #path('', include(router.urls),),
    path('pollsapi/', PollViewSet.as_view(), name='pollsapi'),
    path('pollssingl/', PollSinglListCreate.as_view(), name='pollssingl'),
    path('questionsingl/', QuestionSinglListCreate.as_view(), name='questionsingl'),
    path('pollssinglId/<int:pk>/', PollSinglUpdateDestroyAPIView.as_view(), name='pollssinglId'),
    path('questionsinglId/<int:pk>/', QuestionSinglUpdateDestroyAPIView.as_view(), name='questionsinglId'),
    path('userchoicesingl/<int:pk>/', WriteUserChoiceIDSinglUpdateDestroyAPIView.as_view(), name='userchoicesingl'),
    #path('userchoiceapi/', ListUserChoiceIDList.as_view(), name='userchoiceapi'),
]

apps/polls/urls.py
from django.urls import path
from . import views
from .views import PollView, PollDetail, pollAdd

app_name = 'polls'
urlpatterns = [
    path('', PollView.as_view(), name='polls-list'),
    path('<int:pk>/question/', PollDetail.as_view(), name='poll-detail'),
    path('add/', views.pollAdd, name='poll-add'),
    path('<int:pk>/edit/', views.pollEdit, name='poll-edit'),
    path('<int:pk>/question/add/', views.questionAdd, name='question-add'),
    path('<int:pk>/question/<int:id>/edit/', views.questionEdit, name='question-edit'),
    path('<int:pk>/edit/update/', views.poll_put_, name='poll-put'),#временный метод для запроса в api
]

apps/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('apps.polls_login.urls')),
    path('polls/', include('apps.polls.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('api/v1/', include('api.v1.urls'))
]

apps/polls/models.py
from django.db import models
import uuid
from django.utils.translation import gettext_lazy as _

class Poll(models.Model):
    class Meta:
        db_table = 'poll'
        verbose_name = "Опрос"
        verbose_name_plural = "Опросы"

    title = models.CharField(_("Название"), max_length=256)
    plot = models.CharField(_("Описание"), max_length=512, blank=True)
    start_at = models.DateTimeField(_("Дата старта"), blank=True, null=True)
    end_at =  models.DateTimeField("Дата окончания", blank=True, null=True)
    is_published = models.BooleanField(_("Published"), default=True)

    def __str__(self):
        return '{}'.format(self.title)



class Question(models.Model):
    class Meta:
        db_table = 'question'
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"

    title = models.CharField(_("Название"), max_length=256, blank=True)
    plot = models.CharField(_("Описание"), max_length=512, blank=True)
    poll = models.ForeignKey(Poll, verbose_name=_("Опрос"), on_delete=models.CASCADE, related_name='poll', blank=True, null=True)
    class Type(models.TextChoices):
        INPUT = "Ввод", _("Ввод")
        ONE = "Один", _("Один")
        MANY = "Много", _("Много")
    type = models.CharField(_("Тип"), max_length=32, choices=Type.choices, blank=True)
    choice = models.ManyToManyField('Choice', verbose_name=_("Перечни"), blank=True)

    def __str__(self):
        return self.title



class Choice(models.Model):
    class Meta:
        db_table = 'сhoice'
        verbose_name = "Перечень"
        verbose_name_plural = "Перечни"

    text = models.CharField(verbose_name=_("Перечни"), max_length=256, blank=True)

    def __str__(self):
        return self.text


class UserChoiceID(models.Model):
    class Meta:
        db_table = 'myuser'
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    poll = models.ForeignKey(Poll, verbose_name=_("Опрос"), on_delete=models.SET_NULL, blank=True, null=True)
    question = models.ForeignKey(Question, verbose_name=_("Вопрос"), on_delete=models.SET_NULL, blank=True, null=True)
    choice = models.ForeignKey(Choice, verbose_name=_("Выбор"), on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.uuid, self.choice)

apps/polls/forms.py
from django.forms import ModelForm, Form
from django import forms
from apps.polls.models import Poll, Question


class PollForm(ModelForm):
    class Meta:
        model=Poll
        fields=['title','plot','start_at','end_at', 'is_published']


class ContactForm(Form):
    name=forms.CharField(max_length=50, label="Наименование")
    artist=forms.CharField(max_length=50, label="Исполнитель")
    release=forms.IntegerField(label="Год публикации")
    price=forms.IntegerField(label="Стоимость")

class QuestionForm(ModelForm):
    class Meta:
        model=Question
        fields=['title','plot','type', 'poll', 'choice']

# class NameModelChoiceField(forms.ModelChoiceField):
#     def label_from_instance(self, obj):
#         return "%s"%obj.title

# class StudentForm(forms.Form):
#     title                     = forms.CharField(label='Название', max_length=256)
#     citizenship             = NameModelChoiceField(label = 'Гражданство',queryset  =  Citizenship.objects.order_by('-name'),initial = Citizenship.objects.get(id=1))
#     plot                     = forms.CharField(label='Описание', max_length=512)
#     start_at = forms.DateTimeField(label='Дата старта')
#     end_at =  forms.DateTimeField(label='Дата окончания')

api/v1/polls/views.py
from rest_framework import viewsets, status, permissions, generics
from rest_framework.generics import RetrieveUpdateDestroyAPIView

from apps.polls.models import Poll, Question, UserChoiceID
from api.v1.polls.serializers import PollSerializer, PollSinglSerializer, QuestionSinglSerializer, WriteUserChoiceIDSerializer


"""Полное документация на Swagger 
"""
class PollViewSet(generics.ListAPIView):
    """Полный список расширенний.
    """
    serializer_class = PollSerializer
    queryset = Poll.objects.all()
    permission_classes = [permissions.AllowAny]



class PollSinglListCreate(generics.ListCreateAPIView):
    """Список и запись только опросов"""
    permission_classes = [permissions.AllowAny]
    queryset = Poll.objects.all()
    serializer_class = PollSinglSerializer

class QuestionSinglListCreate(generics.ListCreateAPIView):
    """Список и запись вопросов с приявзкой к опросам и перечням"""
    permission_classes = [permissions.AllowAny]
    queryset = Question.objects.all()
    serializer_class = QuestionSinglSerializer


class PollSinglUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    """
    Изменение, удаление опроса.
    """
    permission_classes = [permissions.AllowAny]
    queryset = Poll.objects.all()
    serializer_class = PollSinglSerializer
    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class QuestionSinglUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    """
    Изменение, удаление вопроса.
    """
    permission_classes = [permissions.AllowAny]
    queryset = Question.objects.all()
    serializer_class = QuestionSinglSerializer
    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class WriteUserChoiceIDSinglUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    """
        Получить, Измененить, Удалить от пользователя данные тестов.
    "poll": id опроса,
    "question": id вопроса,
    "choice": id перечней
    """
    permission_classes = [permissions.AllowAny]
    queryset = UserChoiceID.objects.all()
    serializer_class = WriteUserChoiceIDSerializer



# class ListUserChoiceIDList(generics.ListAPIView):
#     """Полный список пользователей.
#     """
#     serializer_class = ListUserChoiceIDSerializer
#     queryset = UserChoiceID.objects.all()
#     permission_classes = [permissions.AllowAny]

apps/polls/views.py
from django.shortcuts import  redirect
import requests
from django.views.decorators.csrf import csrf_exempt

from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from .models import Poll, Question
from .forms import PollForm, QuestionForm


class PollView(ListView):
    model = Poll
    template_name = 'polls/polls_list.html'
    context_object_name = 'polls'
    queryset = Poll.objects.filter(is_published=True)

class PollDetail(DetailView):
    model = Poll
    template_name = 'polls/polls_detail.html'
    context_object_name = 'poll'
    queryset = Poll.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        ctx = super(PollDetail, self).get_context_data(**kwargs)
        ctx['questions'] = Question.objects.filter(poll=self.kwargs.get('pk'))
        return ctx


def pollAdd(request):  # Форма записи в БД
    pollForm = PollForm
    context = {"pollForm": pollForm, }
    return render(request, "polls/polls_add.html", context)

def pollEdit(request, pk):
    poll = get_object_or_404(Poll, pk=pk)
    pollForm=PollForm(instance=poll)
    context = {"pollForm":pollForm, "pk":pk,}
    return render(request, "polls/polls_edit.html", context)

def questionAdd(request, pk):  # Форма записи в БД
    questionForm = QuestionForm
    context = {"questionForm": questionForm, 'pk':pk, }
    return render(request, "question/question_add.html", context)

def questionEdit(request, pk, id):
    #poll = get_object_or_404(Poll, pk=pk)
    question = get_object_or_404(Question, pk=id)
    questionForm=QuestionForm(instance=question)
    context = {"questionForm":questionForm, "pk":pk,"id":id }
    return render(request, "question/question_edit.html", context)

@csrf_exempt
def poll_put_(request, pk): #Временная обработчик, звамен Ajax
    URL = 'http://127.0.0.1:8000/api/v1/polls/pollssinglId/1/'
    r = requests.put(URL, data=request.POST, headers=dict(Referer=URL))
    return redirect('polls:polls-list')

apps/polls/templates/polls/polls_add.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-1 mb-4">
<h2 style="color:#17A2B8" >Добавить</h2>
<form action = "{% url 'pollssingl' %}" method = "post">
	{% csrf_token %}
	{{ pollForm.as_p }}
	<input type = "submit" id="submit" value = "Submit" />
</form>
</div>
{% endblock %}

apps/polls/templates/polls/polls_detail.html
{% extends 'base.html' %}

{% block content %}

<main class="container mt-5">
    <div class="row">
      <div class="col-12 text-right mb-4">
        <div class="d-flex justify-content-between">
          <h3>Опросы</h3>
            {%  if request.user.is_authenticated  %}
                <a href="{% url 'polls:question-add' pk=poll.id %}" class="btn btn-info">Добавить вопрос</a>
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-info">Войти</a>
            {% endif %}
        </div>
      </div>


    <div class="col-12 text-center my-1">
        <h5 class="mb-3 display-6 text-uppercase">Название: {{ poll.title }}</h5>
        <h5 class="mb-3 display-6 text-uppercase">Описание: {{ poll.plot }}</h5>
         </div> <div class="col-12 text-center my-1">
          <h4>Дата старта:</h4>
           <p><strong>{{ poll.start_at }}</strong></p>
          <h4>Дата окончания:</h4>
           <p><strong>{{ poll.end_at }}</strong></p>
    </div>



{% for question in questions %}
      <div class="card almum-card col-lg-3 col-md-4 col-sm-6 mb-4">
        <div class="card-body">
          <h5 class="card-title">Название: {{ question.title }}</h5>
          <p class="card-text">
      	   <strong>Описание:</strong> {{ question.plot }}
          </p>
            <p class="card-text">
      	   <strong>Опрос: </strong> {{ question.poll }}
          </p>
        <p class="card-text">
      	   <strong>Опрос: </strong> {{ question.type }}
          </p>
            <p class="card-text">
      	   <strong>Перечни: </strong> </br>

            {% if question.type == "Один"  %}


                {% for choice in question.choice.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                    <label for="choice{{ forloop.counter }}">{{ choice }}</label><br /></p>
                {% endfor %}

            {% elif question.type == "Много" %}

                {% for choice in question.choice.all %}
                    <input type="checkbox" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                    <label for="choice{{ forloop.counter }}">{{ choice }}</label><br /></p>
                {% endfor %}

            {% elif question.type == "Ввод" %}

                    <input type="text" name="choice" id="choice" value="" />
                   <br /></p>

            {% endif %}


	     <div class="action-buttons">
             {%  if request.user.is_authenticated  %}
        <a href="{% url 'polls:question-edit' pk=poll.id id=question.id %}" class="btn btn-sm btn-primary"> Edit </a>
        <button id="{{question.id}}" onclick="fun({{question.id}});" class="btn btn-sm btn-danger">Delete</button>
        {% endif %}
         <a href="{% url 'result' user_id=poll.id  %}" class="btn btn-sm btn-primary"> Нажать </a>
         </div>
        </div>
      </div>

{% endfor %}
   </div>
</main>

<style>
.almum-card {
    box-shadow: 0 1rem 1.5rem rgba(0,0,0,.6);
    margin-right: 8px
}
</style>

<script>
  function fun(id_album){

  $.ajax({
  type: 'DELETE',
  url: 'http://localhost:8000/api/album/'+id_album+'/',
  error:function(){ alert('Error!'); return false; },
  success: function(response) {
    console.log(response);
     alert('Успешно удаленно!');
      }});return false;
};
</script>
{% endblock %}

apps/polls/templates/polls/polls_edit.html
{#Редактировать Форма. update: PUT url: /category/1/  Revision of classification details#}


{% extends 'base.html' %}

{% block content %} 
<div class="col-md-1 mb-4">
<h2 style="color:blue">Редактировать</h2>
<form action = "{% url 'polls:poll-put' pk=pk %}" method = "post" >{# Не работает, через PULL- ajax #}
	{% csrf_token %}
    {{pollForm.title.label_tag}}
	{{pollForm.title}}
    {{pollForm.plot.label_tag}}
    {{pollForm.plot}}
    {{pollForm.end_at.label_tag}}
    {{pollForm.end_at}}
    {{pollForm.is_published.label_tag}}
    {{pollForm.is_published}}
	<input  type = "submit" value = "Submit" />
</form>
</div>


{% endblock %}

apps/polls/templates/polls/polls_list.html
{% extends 'base.html' %}

{% block content %}

<main class="container mt-5">
    <div class="row">
      <div class="col-12 text-right mb-4">
        <div class="d-flex justify-content-between">
          <h3>Опросы</h3>
            {%  if request.user.is_authenticated  %}
                <a href="{% url 'polls:poll-add' %}" class="btn btn-info">Добавить опрос</a>
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-info">Войти</a>
            {% endif %}
        </div>

      </div>

{% for poll in polls %}

      <div class="card almum-card col-lg-3 col-md-4 col-sm-6 mb-4">
        <div class="card-body">
          <h5 class="card-title">{{ poll.title }}</h5>
          <p class="card-text">
      	   <strong>Plot:</strong> {{ poll.plot }}
          </p>
	     <div class="action-buttons">
        <a href="{% url 'polls:poll-detail' poll.id %}" class="btn btn-sm btn-success"> View </a>
             {%  if request.user.is_authenticated  %}
        <a href="{% url 'polls:poll-edit' pk=poll.id %}" class="btn btn-sm btn-primary"> Edit </a>
        <button id="{{poll.id}}" onclick="fun({{poll.id}});" class="btn btn-sm btn-danger">Delete</button>
             {% endif %}
       </div>
        </div>
      </div>

{% endfor %}
   </div>
</main>

<style>
.almum-card {
    box-shadow: 0 1rem 1.5rem rgba(0,0,0,.6);
    margin-right: 8px
}
</style>

<script>
  function fun(id){

  $.ajax({

      type: 'DELETE',
      url: 'http://127.0.0.1:8000/api/v1/polls/pollssinglId/'+id+'/',
  error:function(){ alert('Error!'); return false; },
  success: function(response) {
    console.log(response); 
     alert('Успешно удаленно!');
      }});return false;
};
</script>
{% endblock %}